GET http://localhost:5678
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im15a2V5In0.eyJ1c2VyIjoiYW5kcmV3IiwiaWF0IjoxNjgxODU3MzQ4LCJleHAiOjE2ODE4NTgyNDh9.nqZRO3bRBNGhtfnY8ZOGuyfXKReJwDXdvgWSQf4aNZLq92wh1ahRPRo9iAZNhSdeXT-OF-qu36x8mYIdynRhzvR76FTUx-32HwOAYNK3ICkmkgqPsXEPeaMxi4MjAclA_ObjTLbI4jobI3yxanJjQbUAXc9rwQTGPRklBTUn_nNqI-HrpSLbCm5hABeiSrXCzzah5FjbTkSHo9w5WeXV3Gjfmqub-Ob4TPau4fFNbSsx07aTNeuP95Vxi5Bte-xS6afJxaogCvq606EizX0nzLDty4e5MV6j2RBJXOtv54XGoLQpaw8dBJlQ6kcKOCb0e4vBy9QuvewsXIx8W27otg
